export class UserDetail {
    id: string; // ID
    userName: string; // 用户名
    fullName: string; // 姓名
    email: string; // 邮箱
    phoneNumber: string; // 手机号码
    openId: string; // OpenId
    nickName: string; // 昵称
    avatar: string; // 头像
    gender: string; // 性别
    birthday: string; // 生日
    native: string; // 籍贯
    graduate: string; // 毕业院校
    education: string; // 教育
    roles: string[]; // 角色
    groupId: string; // 组织ID
    groupName: string; // 组织名称
    positionId: string; // 岗位ID
    positionName: string; // 岗位名称
}